org.gradle.jvmargs=-Xmx1G
org.gradle.caching=false
org.gradle.configuration-cache=false

# Plugin Metadata
plugin_group=Adathan
plugin_description=Library for useful functionality for boss fights in Hytale by Adathan.
plugin_author=Adathan
plugin_website=
plugin_version = 1.0.7
plugin_main_entrypoint=com.Adathan.AdathansBossLibrary
server_version=2026.02.19-1a311a592
